Blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='Blog'
urlpatterns = [
    path('bloglist/',views.bloglist,name='bloglist'),
    path('blogdetail/<int:articleid>/', views.blogdetail, name='blogdetail'),
    path('comment_create/<int:articleid>/', views.comment_create, name='comment_create'),
]

EndProject/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home.urls',namespace='Home')),
    path('Account/',include('Account.urls',namespace='Account')),
    path('Blog/', include('Blog.urls', namespace='Blog')),
    path('Cart/', include('Cart.urls', namespace='Cart')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from django.db import models
from Account.models import CustomUser

# Create your models here.
class Frame(models.Model):
    frameName = models.CharField(max_length=20)
    numberOfPart = models.PositiveIntegerField()
    numberOfImage = models.PositiveIntegerField()
    htmlFileName = models.CharField(max_length=20)
    image = models.ImageField(upload_to='Frame', blank=True, null=True)

    def __str__(self):
        return self.frameName


class Article(models.Model):
    STATUS_CHOISES =(
        ('pub' , 'Published'),
        ('drf', 'Draft'),
    )
    PRODUCT_STARS = [
        ('1' , 'Very Bad'),
        ('2', 'Bad'),
        ('3', 'Normal'),
        ('4', 'Good'),
        ('5', 'Perfect'),
    ]
    title = models.CharField(max_length=50)
    frame = models.ForeignKey(Frame, on_delete=models.CASCADE)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    author = models.ForeignKey( CustomUser, on_delete=models.CASCADE )
    status = models.CharField(choices=STATUS_CHOISES,max_length=3,default='drf')
    # is_remove = models.BooleanField(default=False) # True / False

    def __str__(self):
        return self.title

    def userscore(self):
        comments = Comment.objects.filter(article=self)
        if comments.count()==0: 
            return(0)
        else:
            sum=0
            for c in comments:
                sum+=int(c.stars)
            return(sum/comments.count())

    def numberOfComments(self):
        comments = Comment.objects.filter(article=self)
        if comments.count()==0:
            return(0)
        else:
            return(Comment.objects.filter(article=self).count())


class ArticlePart(models.Model):
    partTitle = models.CharField(max_length=50)
    text = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    partOrder = models.PositiveIntegerField()

    def __str__(self):
        return self.partTitle


class ArticleImg(models.Model):
    title = models.CharField(max_length=15, default="0")
    image = models.ImageField(upload_to='Frame')
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    imgOrder = models.PositiveIntegerField()

    def __str__(self):
        return self.title


class ArticleLink(models.Model):
    title = models.CharField(max_length=50, default="0")
    link = models.CharField(max_length=150)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    linkOrder = models.PositiveIntegerField()

    def __str__(self):
        return self.title


class SpecialPosition(models.Model):
    title = models.CharField(max_length=20)
    article = models.ForeignKey(Article,on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    PRODUCT_STARS = [
        ('1' , 'Very Bad'),
        ('2', 'Bad'),
        ('3', 'Normal'),
        ('4', 'Good'),
        ('5', 'Perfect'),
    ]
    article = models.ForeignKey(Article,on_delete=models.CASCADE,related_name='comments',)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='comments', )
    body = models.TextField()
    stars = models.CharField(max_length=10,choices=PRODUCT_STARS)
    datetime_create = models.DateTimeField(auto_now_add=True)
    datetime_update = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

Blog/views.py
import datetime
from django.shortcuts import render,redirect
from Home.models import *
from .models import *
from django.core.paginator import Paginator


# Create your views here.
def bloglist(request):
    class counter():
        tour = Tour.objects.all().count()
        airplane = Transport.objects.filter(beginning__type='Pl').count()
        train = Transport.objects.filter(beginning__type='Tr').count()
        bus = Transport.objects.filter(beginning__type='BU').count()
        cruise = Transport.objects.filter(beginning__type='Cr').count()
        residence = Residence.objects.all().count()

    class MyArticle:
        def __init__(self, selectarticle):
            self.id = selectarticle.id
            self.img = ArticleImg.objects.get(article_id=selectarticle.id, imgOrder=1)
            self.part = ArticlePart.objects.get(article_id=selectarticle.id, partOrder=1)
            self.title = selectarticle.title
            self.create = selectarticle.create
            self.month = (datetime.datetime.strptime(str(self.create.month), "%m")).strftime("%b")
            self.update = selectarticle.update
            self.author = selectarticle.author
            self.status = selectarticle.status
    allArticles = Article.objects.all()
    articles = []
    
    for a in allArticles:
        if a.status == 'pub':
            articles.append(MyArticle(a))

    paginator = Paginator(articles,6)
    page_num = request.GET.get('page')
    page_obj = paginator.get_page(page_num)

    context = {
        'articles':page_obj,
        'page_num':page_num,
        'counter':counter,
        # 'articles':articles
    }
    return (render(request,'Blog/bloglist.html',context))


def blogdetail(request, articleid):
    class counter():
        tour = Tour.objects.all().count()
        airplane = Transport.objects.filter(beginning__type='Pl').count()
        train = Transport.objects.filter(beginning__type='Tr').count()
        bus = Transport.objects.filter(beginning__type='BU').count()
        cruise = Transport.objects.filter(beginning__type='Cr').count()
        residence = Residence.objects.all().count()
    class MyArticle:
        def __init__(self, selectarticle):
            self.id = selectarticle.id
            self.parts = ArticlePart.objects.filter(article_id=selectarticle.id).order_by('partOrder')
            # print('selectarticle.id', self.parts[0].partTitle)
            self.images = ArticleImg.objects.filter(article_id=selectarticle.id).order_by('imgOrder')
            self.links = ArticleLink.objects.filter(article_id=selectarticle.id).order_by('linkOrder')
            self.title = selectarticle.title
            self.frame = selectarticle.frame.htmlFileName
            # print('page', self.frame.htmlFileName)
            self.create = selectarticle.create
            self.month = (datetime.datetime.strptime(str(self.create.month), "%m")).strftime("%b")
            self.update = selectarticle.update
            self.author = selectarticle.author
            self.status = selectarticle.status
    # selectedArticle = SpecialPosition.objects.get(title='Homepage')
    myarticle = MyArticle(Article.objects.get(id=articleid))
    comments = Comment.objects.filter(article_id=articleid, active=True)
    context = {
        'counter':counter,
        'myarticle' : myarticle,
        'comments':comments,
    }
    return (render(request,'Blog/blogdetail.html',context))


def comment_create(request, articleid):
    url = request.META.get('HTTP_REFERER')
    comment = Comment(article=Article.objects.get(id=articleid), author=CustomUser.objects.get(id=request.user.id), body=request.POST['message'], stars=request.POST['rate'], active=False)
    comment.save()
    return redirect(url)

Blog/templates/Blog/blogdetail.html
{% extends '_base.html' %}
{% load static %}
{% load djmoney %}
{% block title %}Beik Travel - Blog{% endblock %}
{% block static%}

    <!-- Favicon <link href="img/favicon.ico" rel="icon">-->
    <link href="{ static 'img/favicon.ico' }" rel="icon"/>
    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/newstyle.css' %}" rel="stylesheet">

{%endblock%}
{% block body %}
    
    <!-- Blog Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-3 mt-5 mt-lg-0">
                    <!-- Author Bio -->
                    <div class="d-flex flex-column text-center bg-white mb-5 py-5 px-4">
                        {% if myarticle.author.image %}
                        <img src="{{ myarticle.author.image.url }}" alt="{{ myarticle.author.firstname }}" class="img-fluid mx-auto mb-3" style="width: 100px;">
                        {% endif %}
                        <h3 class="text-primary mb-3">{{ myarticle.author.firstname }}</h3>
                        <div class="d-flex justify-content-center">
                            <a class="text-primary px-2" href="">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a class="text-primary px-2" href="">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a class="text-primary px-2" href="">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                            <a class="text-primary px-2" href="">
                                <i class="fab fa-instagram"></i>
                            </a>
                            <a class="text-primary px-2" href="">
                                <i class="fab fa-youtube"></i>
                            </a>
                        </div>
                    </div>
    
                    <!-- Search Form -->
                    <div class="mb-5">
                        <div class="bg-white" style="padding: 30px;">
                            <div class="input-group">
                                <input type="text" class="form-control p-4" placeholder="Keyword">
                                <div class="input-group-append">
                                    <span class="input-group-text bg-primary border-primary text-white"><i
                                            class="fa fa-search"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Category List -->
                    <div class="mb-5">
                        <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">Categories</h4>
                        <div class="bg-white" style="padding: 30px;">
                            <ul class="list-inline m-0">
                                <li class="mb-3 d-flex justify-content-between align-items-center">
                                    <a class="text-dark" href="#">
                                        <i class="fa fa-angle-right text-primary mr-2"></i>
                                        Tour
                                    </a>
                                    <span class="badge badge-primary badge-pill">{{ counter.tour }}</span>
                                </li>
                                <li class="mb-3 d-flex justify-content-between align-items-center">
                                    <a class="text-dark" href="#">
                                        <i class="fa fa-angle-right text-primary mr-2"></i>
                                        Residence
                                    </a>
                                    <span class="badge badge-primary badge-pill">{{ counter.residence }}</span>
                                </li>
                                <li class="mb-3 d-flex justify-content-between align-items-center">
                                    <a class="text-dark" href="#">
                                        <i class="fa fa-angle-right text-primary mr-2"></i>
                                        Airplane
                                    </a>
                                    <span class="badge badge-primary badge-pill">{{ counter.airplane }}</span>
                                </li>
                                <li class="mb-3 d-flex justify-content-between align-items-center">
                                    <a class="text-dark" href="#">
                                        <i class="fa fa-angle-right text-primary mr-2"></i>
                                        Train
                                    </a>
                                    <span class="badge badge-primary badge-pill">{{ counter.train }}</span>
                                </li>
                                <li class="mb-3 d-flex justify-content-between align-items-center">
                                    <a class="text-dark" href="#">
                                        <i class="fa fa-angle-right text-primary mr-2"></i>
                                        Cruise
                                    </a>
                                    <span class="badge badge-primary badge-pill">{{ counter.cruise }}</span>
                                </li>
                                <li class="d-flex justify-content-between align-items-center">
                                    <a class="text-dark" href="#">
                                        <i class="fa fa-angle-right text-primary mr-2"></i>
                                        Bus
                                    </a>
                                    <span class="badge badge-primary badge-pill">{{ counter.bus }}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
    
                    <!-- Tag Cloud -->
                    <div class="mb-5">
                        <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">Tag Cloud</h4>
                        <div class="d-flex flex-wrap m-n1">
                            <a href="" class="btn btn-light m-1">Travel</a>
                            <a href="" class="btn btn-light m-1">Turism</a>
                            <a href="" class="btn btn-light m-1">Hotel</a>
                            <a href="" class="btn btn-light m-1">Air plan</a>
                            <a href="" class="btn btn-light m-1">Train</a>
                            <a href="" class="btn btn-light m-1">Cruise</a>
                            <a href="" class="btn btn-light m-1">Residence</a>
                            <a href="" class="btn btn-light m-1">Bus</a>
                            <a href="" class="btn btn-light m-1">Tour</a>
                        </div>
                    </div>
                </div>

                <div class="col-lg-9">
                    <!-- <div class="row"> -->
                        <!-- Blog Detail Start -->
                        <div class="col-lg-12">
                            {% include myarticle.frame %}
                        </div>
                        <!-- Blog Detail End -->
                    <!-- </div> -->
                    <!-- <div class="row"> -->
                        <div class="col-lg-12">
                            <!-- Comment List Start -->
                            <div class="bg-white" style="padding: 30px; margin-bottom: 30px;">
                                <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">{{ comments.count }} Comments</h4>
                                {% for c in comments %}
                                <div class="media mb-4">
                                    {% if c.author.image %}
                                    <img src="{{ c.author.image.url }}" alt="{{ c.author.firstname }}" class="img-fluid mr-3 mt-1" style="width: 45px;">
                                    
                                    {% endif %}
                                    <div class="media-body">
                                        <h6><a href="">{{ c.author.firstname }}</a> <small><i>{{ c.datetime_create }}</i></small></h6>
                                        <p>{{ c.body }}</p>
                                        <!-- <button class="btn btn-sm btn-outline-primary">Reply</button> -->
                                    </div>
                                </div>
                                <hr/>
                                {% endfor %}
                            </div>
                            <!-- Comment List End -->
                        </div>
                    <!-- </div> -->
                        
                    {% if user.is_authenticated %}
                    <!-- Comment Form Start -->
                    <div class="bg-white mb-3" style="padding: 30px;">
                        <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">Leave a comment</h4>
                        <form action="{% url 'Blog:comment_create' myarticle.id %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="rate">Rate *</label>
                                <input name="rate" id="rate" type="number" min="0" max="5" value="0" id="rate">
                            </div>
                            <div class="form-group">
                                <label for="message">Message *</label>
                                <textarea name="message" id="message" cols="30" rows="5" class="form-control"></textarea>
                            </div>
                            <div class="form-group mb-0">
                                <input type="submit" value="Leave a comment"
                                    class="btn btn-primary font-weight-semi-bold py-2 px-3">
                            </div>
                        </form>
                    </div>
                    <!-- Comment Form End -->
                    {% endif %}
                </div>
    
                
            </div>
        </div>
    </div>
    <!-- Blog End -->

    {% endblock %}

Blog/templates/Blog/bloglist.html
{% extends '_base.html' %}
{% load static %}
{% load djmoney %}
{% block title %}Beik Travel - Blog{% endblock %}
{% block static%}

    <!-- Favicon <link href="img/favicon.ico" rel="icon">-->
    <link href="{ static 'img/favicon.ico' }" rel="icon"/>
    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/newstyle.css' %}" rel="stylesheet">

{%endblock%}
{% block body %}
    
    <!-- Blog Start -->
    <div class="container-fluid py-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-3 mt-5 mt-lg-0">
                    <!-- Search Form -->
                    <div class="mb-5">
                        <div class="bg-white" style="padding: 30px;">
                            <div class="input-group">
                                <input type="text" class="form-control p-4" placeholder="Keyword">
                                <div class="input-group-append">
                                    <span class="input-group-text bg-primary border-primary text-white"><i
                                            class="fa fa-search"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Category List -->
                    <div class="mb-5">
                        <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">Categories</h4>
                        <div class="bg-white" style="padding: 30px;">
                            <ul class="list-inline m-0">
                                <li class="mb-3 d-flex justify-content-between align-items-center">
                                    <a class="text-dark" href="#">
                                        <i class="fa fa-angle-right text-primary mr-2"></i>
                                        Tour
                                    </a>
                                    <span class="badge badge-primary badge-pill">{{ counter.tour }}</span>
                                </li>
                                <li class="mb-3 d-flex justify-content-between align-items-center">
                                    <a class="text-dark" href="#">
                                        <i class="fa fa-angle-right text-primary mr-2"></i>
                                        Residence
                                    </a>
                                    <span class="badge badge-primary badge-pill">{{ counter.residence }}</span>
                                </li>
                                <li class="mb-3 d-flex justify-content-between align-items-center">
                                    <a class="text-dark" href="#">
                                        <i class="fa fa-angle-right text-primary mr-2"></i>
                                        Airplane
                                    </a>
                                    <span class="badge badge-primary badge-pill">{{ counter.airplane }}</span>
                                </li>
                                <li class="mb-3 d-flex justify-content-between align-items-center">
                                    <a class="text-dark" href="#">
                                        <i class="fa fa-angle-right text-primary mr-2"></i>
                                        Train
                                    </a>
                                    <span class="badge badge-primary badge-pill">{{ counter.train }}</span>
                                </li>
                                <li class="mb-3 d-flex justify-content-between align-items-center">
                                    <a class="text-dark" href="#">
                                        <i class="fa fa-angle-right text-primary mr-2"></i>
                                        Cruise
                                    </a>
                                    <span class="badge badge-primary badge-pill">{{ counter.cruise }}</span>
                                </li>
                                <li class="d-flex justify-content-between align-items-center">
                                    <a class="text-dark" href="#">
                                        <i class="fa fa-angle-right text-primary mr-2"></i>
                                        Bus
                                    </a>
                                    <span class="badge badge-primary badge-pill">{{ counter.bus }}</span>
                                </li>
                            </ul>
                        </div>
                    </div>
    
                    <!-- Tag Cloud -->
                    <div class="mb-5">
                        <h4 class="text-uppercase mb-4" style="letter-spacing: 5px;">Tag Cloud</h4>
                        <div class="d-flex flex-wrap m-n1">
                            <a href="" class="btn btn-light m-1">Travel</a>
                            <a href="" class="btn btn-light m-1">Turism</a>
                            <a href="" class="btn btn-light m-1">Hotel</a>
                            <a href="" class="btn btn-light m-1">Air plan</a>
                            <a href="" class="btn btn-light m-1">Train</a>
                            <a href="" class="btn btn-light m-1">Cruise</a>
                            <a href="" class="btn btn-light m-1">Residence</a>
                            <a href="" class="btn btn-light m-1">Bus</a>
                            <a href="" class="btn btn-light m-1">Tour</a>
                        </div>
                    </div>
                </div>

                <div class="col-lg-9">
                    <div class="row pb-3">
                        {% for a in articles %}
                        <div class="col-md-6 mb-4 pb-2">
                            <div class="blog-item">
                                <div class="position-relative">
                                    <img class="img-fluid w-100 bloglistitem" src="{{ a.img.image.url }}" alt="{{ a.img.title }}">
                                    <div class="blog-date">
                                        <h6 class="font-weight-bold mb-n1">{{ a.create.date.day }}</h6>
                                        <small class="text-white text-uppercase">{{ a.month }}</small>
                                    </div>
                                </div>
                                <div class="bg-white p-4">
                                    <div class="d-flex mb-2">
                                        <a class="text-primary text-uppercase text-decoration-none" href="">{{ a.author.firstname }}</a>
                                        <span class="text-primary px-2">|</span>
                                        <a class="text-primary text-uppercase text-decoration-none" href="">{{ a.author.usertype }}</a>
                                    </div>
                                    <a class="h5 m-0 text-decoration-none" href="{% url 'Blog:blogdetail' a.id %}">{{ a.part.partTitle }}</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="col-12">
                            <nav aria-label="Page navigation">
                                <ul class="pagination pagination-lg justify-content-center bg-white mb-0"
                                style="padding: 30px;">
                                {% if articles.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ articles.previous_page_number }}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ articles.previous_page_number }}">
                                        {{ articles.previous_page_number }}
                                    </a>
                                </li>
                                {% endif %}
                                <li class="page-item active">
                                    <a class="page-link" href="?page={{ articles.number }}">
                                        {{ articles.number }}
                                    </a>
                                </li>
                                {% if articles.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ articles.next_page_number }}">
                                        {{ articles.next_page_number }}
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ articles.next_page_number }}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                                </nav>
                        </div>
                    </div>
                </div>
    
                
            </div>
        </div>
    </div>
    <!-- Blog End -->

    {% endblock %}