Account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='Account'
urlpatterns = [
    path('register/',views.user_register,name='register'),
    path('active/<uidb64>/<token>/',views.RegisterEmail.as_view(),name='active'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    # path('profile/',views.user_profile,name='profile'),
    # path('update/',views.user_update,name='update'),
    # path('change/',views.change_password,name='change'),
    # path('login_phone/',views.phone,name='phone'),
    # path('verify/',views.verify,name='verify'),
    # path('reset/',views.ResetPassword.as_view(),name='reset'),
    # path('reset/done/',views.DonePassword.as_view(),name='reset_done'),
    # path('confirm/<uidb64>/<token>',views.ConfirmPassword.as_view(),name='password_reset_confirm'),
    # path('confirm/done/',views.Complete.as_view(),name='compelet'),
    # path('favourite/',views.favourite,name='favourite'),
    # path('history/',views.history,name='history'),
    # path('view/',views.product_view,name='product_view'),
]

Blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='Blog'
urlpatterns = [
    path('bloglist/',views.bloglist,name='bloglist'),
    path('blogdetail/<int:articleid>/', views.blogdetail, name='blogdetail'),
    path('comment_create/<int:articleid>/', views.comment_create, name='comment_create'),
]

EndProject/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home.urls',namespace='Home')),
    path('Account/',include('Account.urls',namespace='Account')),
    path('Blog/', include('Blog.urls', namespace='Blog')),
    path('Cart/', include('Cart.urls', namespace='Cart')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.urls import path

from . import views


app_name = 'Home'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    path('About/', views.about, name='about'),
    path('Contact/', views.contact, name='contact'),
    path('Services/', views.services, name='services'),
    path('Package/', views.package, name='package'),
    path('Residence/', views.residence, name='residence'),
    path('Transport/', views.transport, name='transport'),
    path('ServicesLoader/', views.servicesLoader, name ='servicesLoader')

    # # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

templates/Booking.html
<!-- Booking Start -->
<div class="container-fluid booking mt-5 pb-5">
    <div class="container pb-5">
        <div class="bg-light shadow" style="padding: 30px;">
            <form method="post" action="{% url 'Home:servicesLoader' %}">
                <div class="row align-items-center" style="min-height: 60px;">
                {% csrf_token %}
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="mb-3 mb-md-0">
                                    <select name="service" class="custom-select px-4" style="height: 47px;" required>
                                        <option disabled selected value="">Service</option>
                                        <!-- <option value="tour">Tour</option> -->
                                        <option value="residence">Residence</option>
                                        <option value="plane">Air plane</option>
                                        <option value="train">Train</option>
                                        <option value="bus">Bus</option>
                                        <option value="cruise">Cruise</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="mb-3 mb-md-0">
                                    <div class="date" id="date1" data-target-input="nearest">
                                        <input name="depart" type="date" class="form-control p-4 datetimepicker-input" placeholder="Depart Date"/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="mb-3 mb-md-0">
                                    <select name="beginning" class="custom-select px-4" style="height: 47px;" >
                                        <option value="NULL" selected>Beginning City</option>
                                        {% for d in destinations %}
                                        <option value="{{ d.city }}">{{ d.city }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="mb-3 mb-md-0">
                                    <select name="destination" class="custom-select px-4" style="height: 47px;" >
                                        <option value="NULL" selected>Destination City</option>
                                        {% for d in destinations %}
                                        <option value="{{ d.city }}">{{ d.city }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <button class="btn btn-primary btn-block" type="submit" style="height: 47px; margin-top: -2px;">Show me!</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Booking End -->

templates/Header.html
<header>
    <!-- Topbar Start -->
    <div class="container-fluid bg-light pt-3 d-none d-lg-block">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 text-center text-lg-left mb-2 mb-lg-0">
                    <div class="d-inline-flex align-items-center">
                        <p><i class="fa fa-envelope mr-2"></i>beik.behrouz@gmail.com</p>
                        <p class="text-body px-3">|</p>
                        <p><i class="fa fa-phone-alt mr-2"></i>+98 937 293 5586</p>
                    </div>
                </div>
                <div class="col-lg-6 text-center text-lg-right">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-primary px-3" href="https://behrouzbeik.ir/Behrouz.html" target="_blank">
                            <i class="fas fa-globe-africa"></i>
                        <a class="text-primary px-3" href="https://www.linkedin.com/in/behrouz-beik-khorasani-70b694134/" target="_blank">
                            <i class="fab fa-linkedin-in"></i>
                        <a class="text-primary px-3" href="https://www.linkedin.com/in/behrouz-beik-khorasani-70b694134/" target="_blank">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="text-primary px-3" href="https://www.linkedin.com/in/behrouz-beik-khorasani-70b694134/" target="_blank">
                            <i class="fab fa-twitter"></i>
                        </a>
                        </a>
                        <a class="text-primary px-3" href="https://www.linkedin.com/in/behrouz-beik-khorasani-70b694134/" target="_blank">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a class="text-primary pl-3" href="https://www.linkedin.com/in/behrouz-beik-khorasani-70b694134/" target="_blank">
                            <i class="fab fa-youtube"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    <!-- Navbar Start -->
    <div class="container-fluid position-relative nav-bar p-0">
        <div class="container-lg position-relative p-0 px-lg-3" style="z-index: 9;">
            <nav class="navbar navbar-expand-lg bg-light navbar-light shadow-lg py-3 py-lg-0 pl-3 pl-lg-5">
                <a href="" class="navbar-brand">
                    <h1 class="m-0 text-primary"><span class="text-dark">Beik </span>Travel</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between px-3" id="navbarCollapse">
                    <div class="navbar-nav ml-auto py-0">
                        <a href="{% url 'Home:index' %}" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'Home:about' %}" class="nav-item nav-link">About</a>
                        <a href="{% url 'Home:services' %}" class="nav-item nav-link">Services</a>
                        <a href="{% url 'Blog:bloglist' %}" class="nav-item nav-link">Blog</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pakages</a>
                            <div class="dropdown-menu border-0 rounded-0 m-0">
                                <a href="{% url 'Home:package' %}" class="dropdown-item">Tour Packages</a>
                                <a href="{% url 'Home:residence' %}" class="dropdown-item">Hotel and Residence</a>
                                <a href="{% url 'Home:transport' %}" class="dropdown-item">Transport</a>
                            </div>
                        </div>
                        <a href="{% url 'Home:contact' %}" class="nav-item nav-link">Contact</a>
                    {% if user.is_authenticated %}
                        <a href="{% url 'Account:logout' %}" class="nav-item nav-link active">Logout</a>
                    {% else %}
                    <a href="{% url 'Home:index' %}#login" class="nav-item nav-link active">Login</a>
                    {% endif %}
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->
</header>

templates/Team.html
<div id="guides" class="container-fluid py-5">
    <div class="container pt-5 pb-3">
        <div class="text-center mb-3 pb-3">
            <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Guides</h6>
            <h1>Our Travel Guides</h1>
        </div>
        <div class="row">
            {% for g in Guides %}
            <div class="col-lg-3 col-md-4 col-sm-6 pb-2">
                <div class="team-item bg-white mb-4">
                    <div class="team-img position-relative overflow-hidden">
                        <img class="img-fluid w-100" src="{{ g.image.url }}" alt="{{ g.firstname }}">
                        <div class="team-social">
                            <a class="btn btn-outline-primary btn-square" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-primary btn-square" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-primary btn-square" href=""><i class="fab fa-instagram"></i></a>
                            <a class="btn btn-outline-primary btn-square" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="text-center py-4">
                        <h5 class="text-truncate">{{ g.firstname }}</h5>
                        <p class="m-0">{{ g.city.city }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            
        </div>
    </div>
</div>

templates/Testimonial.html
<div id="testim" class="container-fluid py-5">
    <div class="container py-5">
        <div class="text-center mb-3 pb-3">
            <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Testimonial</h6>
            <h1>What Say Our Clients</h1>
        </div>
        <div class="owl-carousel testimonial-carousel">
            {% for c in comments %}
            <div class="text-center pb-4">
                {% if c.author.image %}
                <img class="img-fluid mx-auto" src="{{ c.author.image.url }}" alt="{{ c.author.firstname }}" style="width: 100px; height: 100px;" >
                {% endif %}
                <div class="testimonial-text bg-white p-4 mt-n5">
                    <p class="mt-5">{{ c.body }}</p>
                    <h5 class="text-truncate">{{ c.author.firstname }}</h5>
                    <span>{{ c.author.usertype }}</span>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

templates/_base.html
<!DOCTYPE html>
{% load static%}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    
    
    <!---->

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    {% block static %}{% endblock %}
</head>

<body>

    {% include 'Header.html' %}


    {% block body %}{% endblock %}

    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white-50 py-5 px-sm-3 px-lg-5">
        <div class="row pt-5">
            <div class="col-lg-3 col-md-6 mb-5">
                <a href="" class="navbar-brand">
                    <h1 class="text-primary">Beik <span class="text-white">TRAVEL</span></h1>
                </a>
                <p>Sed ipsum clita tempor ipsum ipsum amet sit ipsum lorem amet labore rebum lorem ipsum dolor. No sed vero lorem dolor dolor</p>
                <h6 class="text-white text-uppercase mt-4 mb-3" style="letter-spacing: 5px;">Follow Us</h6>
                <div class="d-flex justify-content-start">
                    <a class="btn btn-outline-primary btn-square mr-2" href="https://www.linkedin.com/in/behrouz-beik-khorasani-70b694134/" target="_blank"><i class="fas fa-globe-africa"></i></a>
                    <a class="btn btn-outline-primary btn-square mr-2" href="https://www.linkedin.com/in/behrouz-beik-khorasani-70b694134/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-outline-primary btn-square mr-2" href="https://www.linkedin.com/in/behrouz-beik-khorasani-70b694134/" target="_blank"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-primary btn-square mr-2" href="https://www.linkedin.com/in/behrouz-beik-khorasani-70b694134/" target="_blank"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-primary btn-square" href="https://www.linkedin.com/in/behrouz-beik-khorasani-70b694134/" target="_blank"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Our Services</h5>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white-50 mb-2" href="{% url 'Home:about' %}"><i class="fa fa-angle-right mr-2"></i>About</a>
                    <a class="text-white-50 mb-2" href="{% url 'Home:index' %}#dest"><i class="fa fa-angle-right mr-2"></i>Destination</a>
                    <a class="text-white-50 mb-2" href="{% url 'Home:services' %}"><i class="fa fa-angle-right mr-2"></i>Services</a>
                    <a class="text-white-50 mb-2" href="{% url 'Home:package' %}"><i class="fa fa-angle-right mr-2"></i>Packages</a>
                    <a class="text-white-50 mb-2" href="{% url 'Home:index' %}#guides"><i class="fa fa-angle-right mr-2"></i>Guides</a>
                    <a class="text-white-50 mb-2" href="{% url 'Home:index' %}#testim"><i class="fa fa-angle-right mr-2"></i>Testimonial</a>
                    <a class="text-white-50" href="{% url 'Home:index' %}#blog"><i class="fa fa-angle-right mr-2"></i>Blog</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Usefull Links</h5>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white-50 mb-2" href="{% url 'Home:about' %}"><i class="fa fa-angle-right mr-2"></i>About</a>
                    <a class="text-white-50 mb-2" href="{% url 'Home:index' %}#dest"><i class="fa fa-angle-right mr-2"></i>Destination</a>
                    <a class="text-white-50 mb-2" href="{% url 'Home:services' %}"><i class="fa fa-angle-right mr-2"></i>Services</a>
                    <a class="text-white-50 mb-2" href="{% url 'Home:package' %}"><i class="fa fa-angle-right mr-2"></i>Packages</a>
                    <a class="text-white-50 mb-2" href="{% url 'Home:index' %}#guides"><i class="fa fa-angle-right mr-2"></i>Guides</a>
                    <a class="text-white-50 mb-2" href="{% url 'Home:index' %}#testim"><i class="fa fa-angle-right mr-2"></i>Testimonial</a>
                    <a class="text-white-50" href="{% url 'Home:index' %}#blog"><i class="fa fa-angle-right mr-2"></i>Blog</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Contact Us</h5>
                <p><i class="fa fa-map-marker-alt mr-2"></i>Mashhad, IRAN</p>
                <p><i class="fa fa-phone-alt mr-2"></i>+98 937 293 5586</p>
                <p><i class="fa fa-envelope mr-2"></i>Beik.behrouz@gmail.com</p>
                <h6 class="text-white text-uppercase mt-4 mb-3" style="letter-spacing: 5px;">Newsletter</h6>
                <div class="w-100">
                    <div class="input-group">
                        <input type="text" class="form-control border-light" style="padding: 25px;" placeholder="Your Email">
                        <div class="input-group-append">
                            <button class="btn btn-primary px-3">Sign Up</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-dark text-white border-top py-4 px-sm-3 px-md-5" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="row">
            <div class="col-lg-6 text-center text-md-left mb-3 mb-md-0">
                <p class="m-0 text-white-50">Copyright &copy; <a href="http://behrouzbeik.pythonanywhere.com/">Turismus Django Portfolio</a>. All Rights Reserved.</a>
                </p>
            </div>
            <div class="col-lg-6 text-center text-md-right">
                <p class="m-0 text-white-50">Designed by <a href="https://behrouzbeik.ir/Behrouz.html">Behrouz Beik Khorasaninia</a>
                </p>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/blogFrame1.html
{% load static %}
<!-- <div class="container-fluid py-5">
    <div class="container pt-5"> -->
        <div class="row">
            <div class="col-lg-6" style="min-height: 500px;">
                <div class="position-relative h-100">
                    <img class="position-absolute w-100 h-100" src="{{ myarticle.images.0.image.url }}" alt="{{ myarticle.title }}" style="object-fit: cover;">
                </div>
            </div>
            <div class="col-lg-6 pt-5 pb-lg-5">
                <div class="about-text bg-white p-4 p-lg-5 my-lg-5">
                    <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">{{ myarticle.title }}</h6>
                    <h1 class="mb-3">{{ myarticle.parts.0.partTitle }}</h1>
                    <p>{{ myarticle.parts.0.text }}</p>
                    <div class="row mb-4">
                        <div class="col-6">
                            <img class="img-fluid" src="{{ myarticle.images.1.image.url }}" alt="{{ myarticle.images.1.title }}">
                        </div>
                        <div class="col-6">
                            <img class="img-fluid" src="{{ myarticle.images.2.image.url }}" alt="{ myarticle.images.2.title }}">
                        </div>
                    </div>
                    <a href="{{ myarticle.links.0.link }}" class="btn btn-primary mt-1">{{ myarticle.links.0.title }}</a>
                </div>
            </div>
        </div>
    <!-- </div>
</div> -->

templates/blogFrame2.html
{% load static %}
<!-- Blog Start -->
<!-- <div class="container-fluid py-5"> -->
    <!-- <div class="container py-5"> -->
        <div class="row">
            <div class="col-lg-12">
                <!-- Blog Detail Start -->
                <div class="pb-3">
                    <div class="blog-item">
                        <div class="position-relative">
                            <img class="img-fluid w-100" src="{{ myarticle.images.0.image.url }}" alt="{{ myarticle.images.0.title }}">
                            <div class="blog-date">
                                <h6 class="font-weight-bold mb-n1">{{ myarticle.create.date.day }}</h6>
                                <small class="text-white text-uppercase">{{ myarticle.month }}</small>
                            </div>
                        </div>
                    </div>
                    <div class="bg-white mb-3" style="padding: 30px;">
                        <div class="d-flex mb-3">
                            <a class="text-primary text-uppercase text-decoration-none" href="">{{ myarticle.author.firstname }}</a>
                            <span class="text-primary px-2">|</span>
                            <a class="text-primary text-uppercase text-decoration-none" href="">{{ myarticle.author.usertype }}</a>
                        </div>
                        <h2 class="mb-3">{{ myarticle.parts.0.partTitle }}</h2>
                        <p>{{ myarticle.parts.0.text }}</p>
                        <h4 class="mb-3">{{ myarticle.parts.1.partTitle }}</h4>
                        <img class="img-fluid w-50 float-left mr-4 mb-2" src="{{ myarticle.images.1.image.url }}" alt="{{ myarticle.images.1.title }}">
                        <p>{{ myarticle.parts.1.text }}</p>
                        <h5 class="mb-3">{{ myarticle.parts.2.partTitle }}</h5>
                        <img class="img-fluid w-50 float-right ml-4 mb-2" src="{{ myarticle.images.2.image.url }}" alt="{{ myarticle.images.2.title }}">
                        <p>{{ myarticle.parts.2.text }}</p>
                    </div>
                </div>
                <!-- Blog Detail End -->

                
                
            </div>

            
        </div>
    <!-- </div> -->
<!-- </div> -->
<!-- Blog End -->

templates/blogFrame3.html
{% load static %}
    <!-- Blog Start -->
            <div class="row bg-white my-5">
                <div class="col-lg-7">
                    <div class="blog-item">
                        <div class="position-relative">
                            <div class="blog-date">
                                <h6 class="font-weight-bold mb-n1">{{ myarticle.create.date.day }}</h6>
                                <small class="text-white text-uppercase">{{ myarticle.month }}</small>
                            </div>
                        </div>
                    </div>
                    <div class="bg-white m-4" style="padding: 30px;">
                        <div class="d-flex mb-3">
                            <a class="text-primary text-uppercase text-decoration-none" href="">{{ myarticle.author.firstname }}</a>
                            <span class="text-primary px-2">|</span>
                            <a class="text-primary text-uppercase text-decoration-none" href="">{{ myarticle.author.usertype }}</a>
                        </div>
                        <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">{{ myarticle.title }}</h6>
                        <h1 class="mb-3">{{ myarticle.parts.0.partTitle }}</h1>
                        <p>{{ myarticle.parts.0.text }}</p>

                        <h6 class="mb-3">{{ myarticle.parts.1.text }}</h6>
                        <a href="{{ myarticle.links.0.link }}" class="btn btn-primary mt-1">{{ myarticle.links.0.title }}</a>
                    </div>
                </div>
                <div class="col-lg-5">
                    <img class="blogdetailimg" src="{{ myarticle.images.0.image.url }}" alt="{{ myarticle.images.0.title }}">
                </div>
                <div class="col-lg-5">
                    <img class="blogdetailimg" src="{{ myarticle.images.1.image.url }}" alt="{{ myarticle.images.1.title }}">
                </div>
                <div class="col-lg-7">
                    <div class="bg-white mb-3" style="padding: 30px;">
                        <h3 class="mb-3">{{ myarticle.parts.2.partTitle }}</h3>
                        <p>{{ myarticle.parts.2.text }}</p>
                        <a href="{{ myarticle.links.1.link }}" class="btn btn-primary mt-1">{{ myarticle.links.1.title }}</a>
                    </div>
                </div>
            </div>
    <!-- Blog End -->